name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - master
pool:
  vmImage: 'ubuntu-latest'
steps:
- script: echo pr id is not null and is $(System.PullRequest.PullRequestId)
  condition: eq(variables['System.PullRequest.PullRequestId'], True)
- script: . .cicd/env.sh
  displayName: 'Set environment'
- script: .cicd/test.sh
  displayName: 'Test'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true
- script: .cicd/build.sh
  displayName: 'Build'
- script: .cicd/docker.sh
  displayName: 'Docker Build'
- task: Docker@2
  displayName: 'Docker Push'
  inputs:
    command: 'push'
    containerRegistry: 'jettech-dockerhub'
    repository: '$(dockerRepo)'
    tags: '$(dockerTag)'
    displayName: 'Push'
    condition: eq(variables['System.PullRequest.PullRequestId'], null)