name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - master
pool:
  vmImage: 'ubuntu-latest'
steps:
- script: |
    . .cicd/env.sh
    echo "##vso[task.setvariable variable=dockerRepo]$dockerRepo"
    echo "##vso[task.setvariable variable=mod]$mod"
    echo "##vso[task.setvariable variable=rev]$rev"
    echo "##vso[task.setvariable variable=vers]$vers"
    echo "##vso[task.setvariable variable=dockerTag]$dockerTag"
    echo "##vso[task.setvariable variable=wat]seriously??"
  displayName: 'Set environment'
- script: echo $(wat)
- script: .cicd/test.sh
  displayName: 'Test'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true
- script: .cicd/build.sh
  displayName: 'Build'
- script: .cicd/docker.sh
  displayName: 'Docker Build'
- task: Docker@2
  displayName: 'Docker Push'
  inputs:
    command: 'push'
    containerRegistry: 'jettech-dockerhub'
    repository: '$(dockerRepo)'
    tags: '$(dockerTag)'
    displayName: 'Push'
    condition: eq(variables['System.PullRequest.PullRequestId'], False)