name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - master
pool:
  vmImage: 'ubuntu-latest'
steps:
- script: .cicd/test.sh
  displayName: 'Test'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true
- script: .cicd/build.sh
  displayName: 'Build'
- script: .cicd/docker.sh
  displayName: 'Docker Build'
- script: echo false
  displayName: 'IsFalse'
  condition: lt(variables['System.PullRequest.PullRequestId'], 1)
- script: echo true
  displayName: 'IsTrue'
  condition: gt(variables['System.PullRequest.PullRequestId'], 0)
- task: Docker@2
  displayName: 'Docker Push'
  condition: lt(variables['System.PullRequest.PullRequestId'], 1)
  inputs:
    command: 'push'
    containerRegistry: 'jettech-dockerhub'
    repository: '$(dockerRepo)' # Set by at least one invocation of .cicd/env.sh
    tags: '$(dockerTag)'
    displayName: 'Push'
